DROP TABLE IF EXISTS raw_data;

CREATE TABLE raw_data (
    customerID VARCHAR(20),
    gender VARCHAR(10),
    SeniorCitizen INT,
    Partner VARCHAR(10),
    Dependents VARCHAR(10),
    tenure INT,
    PhoneService VARCHAR(20),
    MultipleLines VARCHAR(30),
    InternetService VARCHAR(30),
    OnlineSecurity VARCHAR(30),
    OnlineBackup VARCHAR(30),
    DeviceProtection VARCHAR(30),
    TechSupport VARCHAR(30),
    StreamingTV VARCHAR(30),
    StreamingMovies VARCHAR(30),
    Contract VARCHAR(30),
    PaperlessBilling VARCHAR(10),
    PaymentMethod VARCHAR(50),
    MonthlyCharges DECIMAL(10,2),
	TotalCharges DECIMAL(10,2),
	numAdminTickets int,
	numTechTickets int,
    Churn VARCHAR(10)
);

SELECT * from raw_data;

-- total customers 14k
SELECT COUNT(*) AS total_rows,
       COUNT(DISTINCT customerID) AS unique_customers
FROM raw_data;

-- identifying and removing the duplicate records
SELECT customerid, COUNT(*)
FROM raw_data
GROUP BY customerid
HAVING COUNT(*) > 1;


DELETE FROM raw_data
WHERE ctid NOT IN (
    SELECT MIN(ctid)
    FROM raw_data
    GROUP BY customerid
);

--  total customers after cleaning 7k
select count(*) from raw_data;
-- 1. What is the overall customer churn rate?
select count(*) from raw_data where Churn = 'Yes';

SELECT 
    ROUND(
        COUNT(*) FILTER (WHERE churn = 'Yes') * 100.0 / COUNT(*), 
        2
    ) AS churn_rate
FROM raw_data;

--  How much revenue is actually at risk?
select sum(totalcharges) from raw_data where churn = 'Yes';

-- 2. How many customers have churned vs. stayed?
select churn, count(*) as total_customers 
from raw_data
group by churn
order by total_customers;


-- 3. What is the total revenue generated by churned and retained customers?
select churn, round(sum(TotalCharges),2) as total_revenue 
from raw_data
group by churn
order by total_revenue;


-- 4. What is the average monthly charge for churned vs. retained customers?
select churn, round(avg(monthlyCharges),2) as avg_monthly_charges
from raw_data
group by churn
order by avg_monthly_charges;

-- 5. What is the average tenure of churned vs. retained customers?
select churn, round(avg(tenure),2) as avg_tenure 
from raw_data
group by churn
order by avg_tenure;

-- 6. Which contract type has the highest churn rate?
select contract , 
    ROUND(
        COUNT(*) FILTER (WHERE churn = 'Yes') * 100.0 / COUNT(*), 
        2
    )
	AS churn_rate,
	COUNT(*) AS total_customers,
    COUNT(*) FILTER (WHERE churn = 'Yes') AS churned_customers
FROM raw_data
group by contract
order by churn_rate desc;

-- 7. Which internet service type has the highest churn rate?
select internetservice, 
	round(count(*) filter(where churn = 'Yes')*100 / count(*),2)as churn_rate,
	count(*) as totalcustomers,
	count(*) filter (where churn = 'Yes')as churned_cusromers
from raw_data
group by internetservice
order by churn_rate desc;

-- 8. Does having a partner or dependents affect churn?
select partner, dependents, count(*)as total_customers,
	round(count(*) filter(where churn = 'Yes')*100 / count(*),2)as churn_rate,
	count(*)filter (where churn = 'Yes') as churned_customers
from raw_data
group by partner, dependents
order by churn_rate desc;

-- 9. Which age group has higher churn?
select 
	case
		when seniorcitizen = '1' then 'senior citizen'
		else 'non-senior citizen'
	end as age_group,
	count(*)as total_customers,
	count(*) filter(where churn = 'Yes')as churned_customers,
	round(count(*)filter(where churn = 'Yes')*100 / count(*)) as churn_rate
from raw_data
group by age_group
order by churn_rate;

-- 10. Is churn higher among customers with or without phone service?
select phoneservice, 
	round(count(*) filter(where churn = 'Yes')*100 / count(*),2)as churn_rate,
	count(*) as totalcustomers,
	count(*) filter (where churn = 'Yes')as churned_cusromers
from raw_data
group by phoneservice
order by churn_rate desc;

-- 11. Does paperless billing have a relationship with churn?
select paperlessbilling, 
	round(count(*) filter(where churn = 'Yes')*100 / count(*),2)as churn_rate,
	count(*) as totalcustomers,
	count(*) filter (where churn = 'Yes')as churned_cusromers
from raw_data
group by paperlessbilling
order by churn_rate desc;


-- 12. Which payment method has the highest churn rate?
select paymentmethod, 
	round(count(*) filter(where churn = 'Yes')*100 / count(*),2)as churn_rate,
	count(*) as totalcustomers,
	count(*) filter (where churn = 'Yes')as churned_cusromers
from raw_data
group by paymentmethod
order by churn_rate desc;


-- 13. Do customers with higher monthly charges churn more?
select	
	case
		when monthlycharges >=(select percentile_cont(0.75)
		within group(order by monthlycharges)) then 'High Monthly Charges'
		else 'other'
	end as cust_group,
	count(*)as total_customers,
	count(*) filter(where churn = 'Yes')as churned_customers,
	round(count(*)filter(where churn = 'Yes')*100 / count(*)) as churn_rate
from raw_data
group by cust_group
order by churn_rate;

-- 14. Does customer tenure affect churn?
select 
	case
		when tenure <= 6 then '0-6 months'
		when tenure <= 12 then '7-12 months'
		when tenure <= 24 then '13-24 months'
		when tenure <= 48 then '25-48 months'
		else '49+ months'
	end as cust_group,
	count(*)as total_customers,
	count(*) filter(where churn = 'Yes')as churned_customers,
	round(count(*)filter(where churn = 'Yes')*100 / count(*)) as churn_rate
from raw_data
group by cust_group
order by churn_rate desc;
	
-- 15. Do customers with technical support tickets have a higher churn rate?
select 
	case
		when numtechtickets > 0 then 'yes'
		else 'no'
	end as ct,
	count(*)as total_customers,
	count(*) filter(where churn = 'Yes')as churned_customers,
	round(count(*)filter(where churn = 'Yes')*100 / count(*)) as churn_rate
from raw_data
group by ct
order by churn_rate desc;
	
-- 16. Does the number of technical support tickets increase churn?
select numtechtickets,
	count(*)as total_customers,
	count(*) filter(where churn = 'Yes')as churned_customers,
	round(count(*)filter(where churn = 'Yes')*100 / count(*)) as churn_rate
from raw_data
group by numtechtickets
order by churn_rate desc;


-- 17. Does the number of administrative tickets affect churn?
select 
	case
		when numadmintickets > 0 then 'yes'
		else 'no'
	end as ct,
	count(*)as total_customers,
	count(*) filter(where churn = 'Yes')as churned_customers,
	round(count(*)filter(where churn = 'Yes')*100 / count(*)) as churn_rate
from raw_data
group by ct
order by churn_rate desc;


-- 18. Which combination of contract type and internet service has the highest churn rate?
select contract, internetservice,
	count(*)as total_customers,
	count(*) filter(where churn = 'Yes')as churned_customers,
	round(count(*)filter(where churn = 'Yes')*100 / count(*)) as churn_rate
from raw_data
group by contract, internetservice
order by churn_rate desc;


-- 19. Which combination of payment method and contract has the highest churn?
select contract, paymentmethod,
	count(*)as total_customers,
	count(*) filter(where churn = 'Yes')as churned_customers,
	round(count(*)filter(where churn = 'Yes')*100 / count(*)) as churn_rate
from raw_data
group by contract, paymentmethod
order by churn_rate desc;


-- 20. Do customers without Online Security or Tech Support churn more frequently?
select techsupport, onlinesecurity,
	count(*)as total_customers,
	count(*) filter(where churn = 'Yes')as churned_customers,
	round(count(*)filter(where churn = 'Yes')*100 / count(*)) as churn_rate
from raw_data
group by techsupport, onlinesecurity
order by churn_rate desc;

-- 22. Which customer segment has the highest churn based on contract, internet service, and payment method?
select contract, internetservice,paymentmethod,
	count(*)as total_customers,
	count(*) filter(where churn = 'Yes')as churned_customers,
	round(count(*)filter(where churn = 'Yes')*100 / count(*)) as churn_rate
from raw_data
group by contract, internetservice,paymentmethod
order by churn_rate desc
limit 10;


-- 23. Which customer segment generates the highest revenue despite having a high churn rate?
-- 25. Which customer segments have both high churn rate and high revenue contribution?
select contract, internetservice,paymentmethod,
	count(*)as total_customers,
	count(*) filter(where churn = 'Yes')as churned_customers,
	sum(totalcharges)as total_revenue,
	round(count(*)filter(where churn = 'Yes')*100 / count(*)) as churn_rate
from raw_data
group by contract, internetservice,paymentmethod
order by churn_rate desc,total_revenue desc
limit 10;

-- 24. Are high-value customers more likely to churn?
select	
	case
		when monthlycharges >=(select percentile_cont(0.75)
		within group(order by monthlycharges)from raw_data) then 'High Monthly Charges'
		else 'other'
	end as cust_group,
	count(*)as total_customers,
	count(*) filter(where churn = 'Yes')as churned_customers,
	round(count(*)filter(where churn = 'Yes')*100 / count(*)) as churn_rate
from raw_data
group by cust_group;


-- 26. What percentage of churned customers had technical or administrative support tickets?
SELECT 
    ROUND(
        COUNT(*) FILTER (
            WHERE churn = 'Yes'
            AND (numtechtickets > 0 OR numadmintickets > 0)
        ) * 100.0
        /
        COUNT(*) FILTER (WHERE churn = 'Yes'),
        2
    ) AS percentage_of_churned_customers_with_tickets
FROM raw_data;

-- 27. Do customers with multiple support tickets have a significantly higher churn rate?
SELECT 
    CASE
        WHEN (numtechtickets + numadmintickets) = 0 
            THEN '0 Tickets'
        WHEN (numtechtickets + numadmintickets) BETWEEN 1 AND 2 
            THEN '1-2 Tickets'
        ELSE '3+ Tickets'
    END AS ticket_group,
    COUNT(*) AS total_customers,
    COUNT(*) FILTER (WHERE churn = 'Yes') AS churned_customers,
    ROUND(
        COUNT(*) FILTER (WHERE churn = 'Yes') * 100.0 / COUNT(*),
        2
    ) AS churn_rate
FROM raw_data
GROUP BY ticket_group
ORDER BY churn_rate DESC;


-- 30. Who are the top 10 customer segments at highest risk of churn?
SELECT 
    contract,
    internetservice,
    paymentmethod,
    COUNT(*) AS total_customers,
    COUNT(*) FILTER (WHERE churn = 'Yes') AS churned_customers,
    ROUND(
        COUNT(*) FILTER (WHERE churn = 'Yes') * 100.0 / COUNT(*),
        2
    ) AS churn_rate
FROM raw_data
GROUP BY contract, internetservice, paymentmethod
HAVING COUNT(*) >= 50
ORDER BY churn_rate DESC
LIMIT 10;

-- churn rate by contract 
select contract,
	count(*)as total_customers,
	count(*) filter(where churn = 'Yes')as churned_customers,
	round(count(*)filter(where churn = 'Yes')*100 / count(*)) as churn_rate
from raw_data
group by contract
order by churn_rate desc;









SELECT 
    'Online Security' AS service,
    onlinesecurity AS service_status,
    COUNT(*) AS total_customers,
    COUNT(*) FILTER (WHERE churn = 'Yes') AS churned_customers,
    ROUND(
        COUNT(*) FILTER (WHERE churn = 'Yes') * 100.0 / COUNT(*),
        2
    ) AS churn_rate
FROM raw_data
GROUP BY onlinesecurity

UNION ALL

SELECT 
    'Tech Support' AS service,
    techsupport AS service_status,
    COUNT(*) AS total_customers,
    COUNT(*) FILTER (WHERE churn = 'Yes') AS churned_customers,
    ROUND(
        COUNT(*) FILTER (WHERE churn = 'Yes') * 100.0 / COUNT(*),
        2
    ) AS churn_rate
FROM raw_data
GROUP BY techsupport

UNION ALL

SELECT 
    'Online Backup' AS service,
    onlinebackup AS service_status,
    COUNT(*) AS total_customers,
    COUNT(*) FILTER (WHERE churn = 'Yes') AS churned_customers,
    ROUND(
        COUNT(*) FILTER (WHERE churn = 'Yes') * 100.0 / COUNT(*),
        2
    ) AS churn_rate
FROM raw_data
GROUP BY onlinebackup

UNION ALL

SELECT 
    'Device Protection' AS service,
    deviceprotection AS service_status,
    COUNT(*) AS total_customers,
    COUNT(*) FILTER (WHERE churn = 'Yes') AS churned_customers,
    ROUND(
        COUNT(*) FILTER (WHERE churn = 'Yes') * 100.0 / COUNT(*),
        2
    ) AS churn_rate
FROM raw_data
GROUP BY deviceprotection

ORDER BY service, churn_rate DESC;




